### ISSUE TITLE
bug: No highlights for boolean values

### ISSUE THREAD

**Issue by mkblast** [tree-sitter-grammars/tree-sitter-zig#3]
### Did you check existing issues?

- [x] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [x] I have searched the existing issues

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.24.3 (bdfe32402e85673bbc693216f0a6ef72c98bb665)

### Describe the bug

Seems like boolean values like true of false are not highlighted:
![Image](https://github.com/user-attachments/assets/fc395076-dee7-42d8-8480-09b9ffd3dca8)

in other languages (rust):
![Image](https://github.com/user-attachments/assets/e6af1142-1fc9-4969-aa18-8fd282b69dfa)

### Steps To Reproduce/Bad Parse Tree

1. Open zig file.
2. create a variable that holds a boolean.
3. no highlights. 

### Expected Behavior/Parse Tree

non.

**Comment by xdBronch** [comment]
it seems true and false are classified as `identifier`, id bet if your theme highlighted those differently it would change true/false too
(ignore highlighting im not using ts for that)
![Image](https://github.com/user-attachments/assets/4eaaa531-3834-44d8-a6ee-fd0a41bed23b)
these 4 variables correspond to this tree in nvims `:InspectTree`
![Image](https://github.com/user-attachments/assets/3d1b8639-d340-440b-9b23-dca64874e7e1)
notice how `t` and `f` have 2 `(identifier)` nodes
